version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - PHP_MEMORY_LIMIT=256M # Example to set memory limit (if needed)
